---
title: "Life Changing - Helen Pilcher"
---

In “Life Changing: How Humans are Shaping the Course of Evolution”, Helen Pilcher explores how humans have fundamentally altered life on Earth. In this book, Pilcher argues that “Life is changing. Humans are responsible”. Her guide on the ‘post-natural’ history of our world showcases, in three parts, how we shape our surroundings: how we have unwittingly advanced some species, how we purposefully tailor species to our wants and needs, and finally, how we can harness this knowledge to assist conservation efforts. Pilcher discusses these themes with a strong focus on genetics and evolution. She supports her argument through tackling concepts such as genetic modification and assisted evolution by discussing broad topics like domestication, selective breeding, artificial insemination, cloning, de-extinction, hybridisation, and rewilding.

As a former scientific reporter with a PhD in stem cell biology, Pilcher understands the importance of both communicating science accurately and correcting false beliefs. As a former stand-up comedian, she also understands the importance of making difficult content relatable through quick wit and an occasional acerbic joke. She immediately establishes this as a concrete idea that ancient domestication of animals and plants is a form of genetic modification, albeit distinct from modern, laboratory-based methods in degree rather than kind – she says about her dog or ‘genetically modified wolf’ that “*The result is an animal so far removed from its original wild form that he barks at bin bags and often refuses to go out in the rain*”. Pilcher also corrects common misbeliefs surrounding cloning – clarifying that it does not produce an exact genetic replica but rather an “identical twin”,  illustrating her point by comparing the difference in scrotal circumference of two clones – the “*prolific beef sires*” (Final Answer and Final Answer II). Furthermore, she amends the notion of de-extinction as resurrection by explaining that it involves modifying a closely related species to resemble its extinct ancestor, describing them as a “*hybrid modern-day facsimile*”.

Pilcher deftly communicates her viewpoints while acknowledging opposing beliefs and even potential benefits to some practices with which she may disagree. She subtly hints at issues surrounding overpopulation and excessive meat consumption without being accusatory or condescending. She approaches depressing topics such as animal suffering and climate change with a determined optimism and offers silver-lined solutions. While Pilcher’s bias toward rewilding is evident in her abundant praise, she could have more fully explained the controversy and debate surrounding the topic. In this area, mentioning a more integrated approach combining rewilding efforts with regenerative farming practices and reduced meat consumption could have provided a more balanced perspective on creating healthier agricultural systems, rather than relying mainly on rewilding.

“Life Changing” stands out among others in this genre concerning altered species, genetics, evolution, and climate change. Pilcher’s extensive understanding and thorough research, coupled with her wicked sense of humour, allow readers to grasp even the most complex subjects with ease. From the outset, it’s clear that Pilcher possesses a rare talent for communicating nuanced ideas with clarity and wit in an unbiased manner. She guides the reader through each topic with an intuitive flow, gradually building understanding and solidifying concepts with excellently timed quips.

“Life Changing” presents a solid foundation for understanding how we influence the genetic make-up and evolution of other species, as well as our overall impact on the world. While not an exhaustive text, it offers insight into our past influences and provides suggestions on how to proceed responsibly moving forward. Accessible enough for the uninitiated dilettante yet profound enough for the specialist savant, this book broadens intellectual horizons across the spectrum. Pilcher’s engaging writing style delivered a must-read to those looking to expand their knowledge or those wanting a casual read.
